### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by caitlin-hutnyk** [DDMAL/mei-mapping-tool#168]
- [x] Refactor views, specifically merge the different project views to one
- [x] Remove long scripts from jade files (#170)
- [x] Remove redundant/deprecated scripts and functions (#170)
- [x] Fix route/url and function naming scheme, and keep related functions in the same files (#171)
- [x] Add comments and documentation (#172)
- [x] Fix logging and error trapping (#172)

**Comment by caitlin-hutnyk** [comment]
#175
